---
title: "p1805_ma4705_hw2"
output: github_document
date: "2025-10-04"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
```

# Problem 1
* clean pols-month data
```{r pols_month}
pols_month_df <- read_csv("./datasets/pols-month.csv") |>
  janitor::clean_names() |>
  separate(mon, c("year", "month", "day"), sep = "-") |>
  mutate(year = substr(year, 3, 4), month = month.name[as.numeric(month)],
         president = factor(prez_gop, levels = c(0, 1), labels = c("dem", "gop"))) |>
  select(-day, -prez_gop, -prez_dem) |>
  relocate(year, month, president)

pols_month_df
```
* clean snp data
```{r snp}
snp_df <- read_csv("./datasets/snp.csv") |>
  janitor::clean_names() |>
  separate(date, c("month", "day", "year"), sep = "/") |>
  mutate(month = month.name[as.numeric(month)]) |>
  select(-day) |>
  relocate(year, month)

snp_df
```
* clean unemployment data
```{r unemployment}
unemployment_df <- read_csv("./datasets/unemployment.csv") |>
  pivot_longer(Jan:Dec, names_to = "month", values_to = "unempl_perc") |>
  mutate(month = as.character(factor(month, levels = month.abb, labels = month.name))) |>
  janitor::clean_names() |>
  mutate(year = substr(as.character(year), 3, 4))

unemployment_df
```
* merge pols-month and snp data
```{r merge_pols_snp}
pols_snp_df = left_join(pols_month_df, snp_df)
pols_snp_df
```

* merge with unemployment data
```{r merge_unemployment}
pols_snp_unemp_df = left_join(pols_snp_df, unemployment_df) |> select(year, month, president, close, unempl_perc)
pols_snp_unemp_df
```
# Problem 2
```{r mrtrashweel}
mrtrashweel_df = read_excel("./datasets/202509 Trash Wheel Collection Data.xlsx", sheet = "Mr. Trash Wheel") |>
  janitor::clean_names() |>
  drop_na(dumpster) |>
  mutate(year = as.numeric(year), sports_balls = round(sports_balls), trash_wheel = "MTW", trash_wheel = factor(trash_wheel, levels = c("MTW", "GF"), labels= c("Mr. Trash Wheel", "Gwynns Falls")))

mrtrashweel_df
```
```{r gwynn_falls_trashweel}
gftrashwheel_df = read_excel("./datasets/202509 Trash Wheel Collection Data.xlsx", sheet = "Gwynns Falls Trash Wheel") |>
  janitor::clean_names() |>
  drop_na(dumpster) |>
  mutate(trash_wheel = "GF", trash_wheel = factor(trash_wheel, levels = c("MTW", "GF"), labels= c("Mr. Trash Wheel", "Gwynns Falls")))

gftrashwheel_df
```
```{r combined trashwheel_df}
trashwheel_df = left_join(mrtrashweel_df, gftrashwheel_df)
trashwheel_df
```
# Problem 3
